version: "3"
services:
  app-database:
    image: mongo:latest
    container_name: "app-database"
    ports:
      - 27017:27017
  app:
    image: app
    container_name: app
    ports:
      - 8080:8080
    links:
      - app-database